# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designator', models.CharField(max_length=4)),
                ('start_date', models.DateField()),
                ('graduation_date', models.DateField()),
                ('website', models.CharField(max_length=255)),
            ],
        ),
    ]
